language: python
python:
  - "3.6"
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
# command to install dependencies
install: make setup
# # command to run tests
script:
  -	pipenv shell
  -	python test/generate_test_data.py
  -	python -m pytest test
